### ISSUE TITLE
disable build buddy by default

### ISSUE THREAD

**Issue by will-camus** [thundergolfer/example-bazel-monorepo#52]
## Description of the problem / feature request:
please disable build buddy by default [ and remove https://app.buildbuddy.io/invocation/9a58fab0-e62e-4034-875d-b382e5f9a42b ]

**Comment by thundergolfer** [comment]
Hey, can you say why?

**Comment by will-camus** [comment]
I found it surprising that an example repo by default sent potentially sensitive telemetry from my machine, including OS, username, etc. to a remote server without being able to opt-in or out interactively. I would not have run the example if I had known that the telemetry would be sent.

**Comment by thundergolfer** [comment]
Ok yep, I can understand that. I can comment out the line in the `.bazelrc` and make it opt-in.
