### ISSUE TITLE
Why BUILD.bazel over BUILD?

### ISSUE THREAD

**Issue by kkweon** [thundergolfer/example-bazel-monorepo#6]
https://github.com/thundergolfer/the-one-true-bazel-monorepo/blob/7a11ce0e890efc997b384414430a94c2384072f0/fruit_sorting/BUILD.bazel

I think using BUILD is the best as it is consistent with the official doc. I understand if it may have a syntax highlighting issue depending on what you use but that should be the syntax highlighting plug-in issue that it should recognize BUILD as a Bazel file.

**Comment by thundergolfer** [comment]
Sorry for late reply, 

Both work, but I'm used to `BUILD.bazel` because during a migration we had other `build` files lying around causing conflicts.

I can change it.

**Comment by thundergolfer** [comment]
Closed by 677259a
